# Generated by Django 4.2.4 on 2023-08-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altkategori',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altkategori', to='etkinlik.kategori'),
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('altkategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik', to='etkinlik.altkategori')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik', to='etkinlik.kategori')),
            ],
        ),
    ]
