# Generated by Django 4.2.4 on 2023-08-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0002_alter_altkategori_kategori_etkinlik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='isim',
        ),
        migrations.AddField(
            model_name='kategori',
            name='ad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategori',
            name='ust_kategori',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='etkinlik.kategori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
