# Generated by Django 4.2.4 on 2023-08-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0003_remove_kategori_isim_kategori_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='ust_kategori',
        ),
        migrations.AddField(
            model_name='altkategori',
            name='ust_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='etkinlik.altkategori'),
        ),
        migrations.AlterField(
            model_name='altkategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
