# Generated by Django 4.2.4 on 2023-08-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anakategori',
            old_name='level',
            new_name='mptt-level',
        ),
    ]
