# Generated by Django 4.2.4 on 2023-08-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0009_rename_level_anakategori_mptt_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnaKategori',
            new_name='Kategori',
        ),
    ]
