# Generated by Django 4.2.4 on 2023-08-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0010_rename_anakategori_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etkinlik.kategori'),
        ),
    ]
