# Generated by Django 4.2.4 on 2023-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0013_alter_etkinlik_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
