# Generated by Django 4.2.4 on 2023-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0016_alter_kategori_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='etkinlik_tarihi',
            field=models.DateTimeField(null=True),
        ),
    ]
