# Generated by Django 4.2.4 on 2023-08-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0018_etkinlik_etkinlik_resim_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etkinlik',
            old_name='parent',
            new_name='kategori',
        ),
    ]
