# Generated by Django 4.2.4 on 2023-08-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0021_alter_etkinlikmekan_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='mekan_resim',
            field=models.FileField(upload_to='etkinlik/', verbose_name='Mekan Resmi'),
        ),
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='oturma_plani_resim',
            field=models.FileField(upload_to='etkinlik/', verbose_name='Oturma Planı'),
        ),
    ]
