# Generated by Django 4.2.4 on 2023-08-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0022_alter_etkinlikmekan_mekan_resim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlikmekan',
            name='sehir',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='aciklama',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='adres',
            field=models.TextField(max_length=500),
        ),
    ]
