# Generated by Django 4.2.4 on 2023-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0023_etkinlikmekan_sehir_alter_etkinlikmekan_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='aciklama',
            field=models.TextField(max_length=550),
        ),
    ]
