# Generated by Django 4.2.4 on 2023-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0025_etkinlik_is_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='etkinlik_resim_profil',
            field=models.FileField(blank=True, upload_to='etkinlik/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='mekan_resim',
            field=models.FileField(blank=True, upload_to='etkinlik/', verbose_name='Mekan Resmi'),
        ),
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='mekan_resim_profil',
            field=models.FileField(blank=True, upload_to='etkinlik/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='etkinlikmekan',
            name='oturma_plani_resim',
            field=models.FileField(blank=True, upload_to='etkinlik/', verbose_name='Oturma Planı'),
        ),
    ]
