# Generated by Django 4.2.4 on 2023-08-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0026_alter_etkinlik_etkinlik_resim_profil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etkinlik',
            old_name='is_home',
            new_name='is_carousel',
        ),
    ]
