# Generated by Django 4.2.4 on 2023-08-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0027_rename_is_home_etkinlik_is_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etkinlik',
            old_name='is_carousel',
            new_name='one_cikan_index',
        ),
    ]
