# Generated by Django 4.2.4 on 2023-08-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0031_etkinlik_muzik_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='aile_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='sahne_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='spor_index',
            field=models.BooleanField(default=False),
        ),
    ]
