# Generated by Django 4.2.4 on 2023-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0032_etkinlik_aile_index_etkinlik_sahne_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='one_cikan_self',
            field=models.BooleanField(default=False),
        ),
    ]
