# Generated by Django 4.2.4 on 2023-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0033_etkinlik_one_cikan_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlik',
            name='one_cikan_self',
        ),
    ]
