# Generated by Django 4.2.4 on 2023-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0034_remove_etkinlik_one_cikan_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='etkinlik_banner_resim',
            field=models.FileField(blank=True, upload_to='etkinlik/banner', verbose_name='Banner Resmi'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='etkinlik_carousel_resim',
            field=models.FileField(blank=True, upload_to='etkinlik/carousel', verbose_name='Carousel Resmi'),
        ),
    ]
