# Generated by Django 4.2.4 on 2023-08-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0038_etkinlik_carousel_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='stok',
            field=models.BooleanField(default=False),
        ),
    ]
