# Generated by Django 4.2.4 on 2023-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0040_alter_etkinlikmekan_mekan_resim_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='kategori_resim',
            field=models.FileField(blank=True, upload_to='kategori/', verbose_name='Kategori Resmi'),
        ),
    ]
