# Generated by Django 4.2.4 on 2023-08-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0041_kategori_kategori_resim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='kategori_resim',
            new_name='altkategori_resim',
        ),
    ]
