# Generated by Django 4.2.4 on 2023-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0042_rename_kategori_resim_kategori_altkategori_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='fiyat',
            field=models.PositiveIntegerField(default=250),
            preserve_default=False,
        ),
    ]
