# Generated by Django 4.2.4 on 2023-09-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0048_sepet_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
