# Generated by Django 4.2.4 on 2023-09-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0049_sepet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
