# Generated by Django 4.2.4 on 2023-09-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0050_alter_sepet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepet',
            name='slug',
        ),
    ]
