# Generated by Django 4.2.4 on 2023-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0051_remove_sepet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
