# Generated by Django 4.2.4 on 2023-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0052_alter_etkinlik_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
