# Generated by Django 4.2.4 on 2023-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0054_remove_sepet_slug_alter_etkinlik_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
