# Generated by Django 4.2.4 on 2023-09-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0056_müsteri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='müsteri',
            old_name='e_posta',
            new_name='email',
        ),
    ]
