# Generated by Django 4.2.4 on 2023-09-04 21:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etkinlik', '0057_rename_e_posta_müsteri_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Müsteri',
            new_name='Musteri',
        ),
    ]
