# Generated by Django 4.2.4 on 2023-09-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0059_alter_musteri_cinsiyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='adres',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='cep_telefonu',
            field=models.CharField(max_length=25),
        ),
    ]
