# Generated by Django 4.2.4 on 2023-09-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0060_musteri_adres_alter_musteri_cep_telefonu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='adres',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
