# Generated by Django 4.2.4 on 2023-09-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0061_alter_musteri_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='adres',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
