# Generated by Django 4.2.4 on 2023-09-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0064_adres_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='adres',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='etkinlik.adres'),
        ),
    ]
