# Generated by Django 4.2.4 on 2023-09-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0066_remove_musteri_adres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adres',
        ),
    ]
