# Generated by Django 4.2.4 on 2023-09-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0070_etkinlik_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='hot_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
