# Generated by Django 4.2.4 on 2023-09-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0073_adres_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adres',
            old_name='adres_baslık',
            new_name='adres_baslik',
        ),
    ]
