# Generated by Django 4.2.4 on 2023-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0074_rename_adres_baslık_adres_adres_baslik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='fiyat',
            field=models.PositiveIntegerField(),
        ),
    ]
